version: 0.2

phases:
  install:
    commands:
      - npm install --save
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
